import ace from 'ace-builds';
import modeCCppUrl from 'ace-builds/src-noconflict/mode-c_cpp?url';
import modeJavascript from 'ace-builds/src-noconflict/mode-javascript?url';
import modePythonUrl from 'ace-builds/src-noconflict/mode-python?url';
import modeSqlUrl from 'ace-builds/src-noconflict/mode-sql?url';
import modeHtmlUrl from 'ace-builds/src-noconflict/mode-html?url';
import modeTextUrl from 'ace-builds/src-noconflict/mode-text?url';
import themeGithubUrl from 'ace-builds/src-noconflict/theme-github?url';
import themeChromeUrl from 'ace-builds/src-noconflict/theme-chrome?url';
import themeMonokaiUrl from 'ace-builds/src-noconflict/theme-monokai?url';
import themeDreamweaverUrl from 'ace-builds/src-noconflict/theme-dreamweaver?url';
import themeEclipseUrl from 'ace-builds/src-noconflict/theme-eclipse?url';
import workerBaseUrl from 'ace-builds/src-noconflict/worker-base?url';
import snippetsCCppUrl from 'ace-builds/src-noconflict/snippets/c_cpp?url';
import snippetsJavascriptUrl from 'ace-builds/src-noconflict/snippets/javascript?url';
import snippetsPythonUrl from 'ace-builds/src-noconflict/snippets/python?url';
import snippetsHtmlUrl from 'ace-builds/src-noconflict/snippets/html?url';
import snippetsTextUrl from 'ace-builds/src-noconflict/snippets/text?url';
import 'ace-builds/src-noconflict/ext-language_tools';

ace.config.setModuleUrl('ace/mode/c_cpp', modeCCppUrl);
ace.config.setModuleUrl('ace/mode/javascript', modeJavascript);
ace.config.setModuleUrl('ace/mode/python', modePythonUrl);
ace.config.setModuleUrl('ace/mode/sql', modeSqlUrl);
ace.config.setModuleUrl('ace/mode/html', modeHtmlUrl);
ace.config.setModuleUrl('ace/mode/text', modeTextUrl);
ace.config.setModuleUrl('ace/theme/github', themeGithubUrl);
ace.config.setModuleUrl('ace/theme/chrome', themeChromeUrl);
ace.config.setModuleUrl('ace/theme/monokai', themeMonokaiUrl);
ace.config.setModuleUrl('ace/theme/dreamweaver', themeDreamweaverUrl);
ace.config.setModuleUrl('ace/theme/eclipse', themeEclipseUrl);
ace.config.setModuleUrl('ace/mode/base', workerBaseUrl);
ace.config.setModuleUrl('ace/snippets/c_cpp', snippetsCCppUrl);
ace.config.setModuleUrl('ace/snippets/sql', snippetsJavascriptUrl);
ace.config.setModuleUrl('ace/snippets/python', snippetsPythonUrl);
ace.config.setModuleUrl('ace/snippets/html', snippetsHtmlUrl);
ace.config.setModuleUrl('ace/snippets/text', snippetsTextUrl);
ace.require("ace/ext/language_tools");
